
spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/orclpdb
    username: hr
    password: hr
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        sql: true
        dialect: org.hibernate.dialect.OracleDialect
        jdbc:
          batch_size: 50  # enables JDBC batching and sets the batch size to 50
        order_inserts: true # tells Hibernate to group INSERT statements of the same entity
        order_updates: true
        format_sql: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:y8P2Q1v+K9L0rT5sD7X3zA4bU6mN8cW1eF0G2hI7jL9kM5pR} # Use env var in prod
  expiration: 900000 # 15 minutes in milliseconds
  refresh-expiration: 604800000 # 7 days

stripe:
  api:
    key: ${STRIPE_API_KEY}
